    apiVersion: v1
    kind: Service
    metadata:
      name: stock-picker-service
    spec:
      type: NodePort
      selector:
        app: stock-picker
      ports:
        - protocol: TCP
          port: 80
          targetPort: 8080